APT::FTPArchive::Release {
  Origin "certfix";
  Label "certfix repo";
  Suite "stable";
  Codename "stable";
  Architectures "amd64 arm64";
  Components "main";
  Description "Certfix APT Repository";
};
